train: "train.txt"
val: "val.txt"
pretrained_path: "/home/thaind/anonymous_project/Cosmos/ckpt/Cosmos-Tokenize1-CV8x8x8-720p/autoencoder.jit"
EPOCH: 20
ckpt: "ckpt"
save_path: "save_image"
lr: 0.0001
ssim: True